dependencies:
- name: demo1110
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- name: golang-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: node-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: starter1110
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.1
